[ui]
# Hide the top bar completely
hideTopBar = true

[browser]
# Disable usage stats collection
gatherUsageStats = false

[theme]
primaryColor = "#434373"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Plus Jakarta Sans:https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap"
codeFont = "'Space Mono':https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"


blueColor = "#434373"

categoricalColors = [
    "#434373",
    "#16C49A",
    "#FF9068",
    "#FF7747",
    "#13A181",
    "#20E8B5",
    "#FF4081",
    "#FFE32C",
    "#6A1EBB",
    "#4A4A4A"
]

chartSequentialColors = [
    "#434373",
    "#16C49A",
    "#FF9068",
    "#FF7747",
    "#13A181",
    "#20E8B5",
    "#FF4081",
    "#FFE32C",
    "#6A1EBB",
    "#4A4A4A"
]
[theme.sidebar]
backgroundColor = "#F9F5FF"

[server]
headless = true
maxUploadSize = 10000
